FROM node:20-slim@sha256:11b92dfb7eafe32774f1b3e78e5f3a458cb9bdcce8c5c2a7f194289da0382de4

WORKDIR /usr/src/app

COPY package*.json ./

RUN apt-get update && apt-get install -y curl

RUN groupadd -r appuser && useradd -r -g appuser -d /usr/src/app -s /sbin/nologin -c "Docker image user" appuser && chown -R appuser:appuser /usr/src/app

RUN npm install -g pnpm && pnpm install

COPY --chown=appuser:appuser . .

USER appuser

RUN pnpm run build

EXPOSE 3000

CMD ["pnpm", "run", "start:prod"]
